insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (24, 12, 36, 1, 'In quis justo.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (2, 21, 30, 1, 'Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (11, 45, 31, 1, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (19, 50, 32, 5, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (2, 62, 8, 5, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (20, 33, 23, 5, 'Morbi a ipsum. Integer a nibh.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (18, 81, 33, 2, 'In sagittis dui vel nisl. Duis ac nibh.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (7, 90, 4, 4, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (2, 79, 48, 3, 'Donec ut dolor.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (12, 26, 50, 2, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (17, 24, 44, 2, 'In hac habitasse platea dictumst.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (21, 97, 42, 3, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (5, 37, 50, 3, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (23, 29, 31, 4, 'Duis at velit eu est congue elementum.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (21, 33, 35, 2, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (21, 51, 44, 4, 'Integer a nibh. In quis justo.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (23, 27, 30, 1, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (16, 50, 9, 1, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (2, 7, 43, 3, 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (5, 17, 9, 3, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (17, 78, 21, 1, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (17, 2, 50, 2, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (18, 46, 8, 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (23, 40, 10, 2, 'Aenean lectus.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (22, 14, 49, 2, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (15, 69, 16, 2, 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (14, 98, 25, 2, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (7, 68, 36, 5, 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (21, 77, 36, 1, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (5, 2, 8, 2, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (17, 22, 24, 5, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (20, 83, 41, 4, 'Curabitur convallis.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (11, 80, 11, 1, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (20, 78, 9, 2, 'Phasellus id sapien in sapien iaculis congue.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (20, 57, 7, 3, 'Donec semper sapien a libero. Nam dui.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (3, 29, 12, 3, 'In hac habitasse platea dictumst.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (2, 75, 8, 1, 'Morbi porttitor lorem id ligula.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (10, 22, 35, 1, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (14, 31, 49, 1, 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (13, 86, 44, 5, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (21, 4, 47, 1, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (13, 71, 3, 5, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (25, 72, 48, 5, 'Sed ante. Vivamus tortor.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (12, 9, 2, 3, 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (5, 12, 1, 1, 'Praesent blandit lacinia erat.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (5, 63, 42, 4, 'Nullam porttitor lacus at turpis.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (22, 62, 40, 5, 'Ut at dolor quis odio consequat varius.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (3, 73, 34, 2, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (11, 54, 18, 4, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into property_reviews (guest_id, property_id, reservation_id, rating, message) values (3, 25, 16, 1, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
